#!/usr/bin/env bash
# Configures a brand new Ubuntu machine to the redirection requirements
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.html

CONFIGURED=$(grep -c "error_page 404 /404-error.html;" /etc/nginx/sites-enabled/default)

if [ "$CONFIGURED" = 0 ]; then
    sed -i '/listen \[::\]:80 default_server;/a \\n\terror_page 404 /404-error.html;' /etc/nginx/sites-enabled/default
    echo "Ceci n'est pas une page" > /var/www/html/404-error.html
fi
