#!/usr/bin/env bash
# This script will:
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

trap ctrl_c INT
trap kill_process SIGTERM SIGQUIT

function kill_process()
{
	echo "I hate the kill command"
	sudo rm /var/run/holbertonscript.pid
	sudo kill -SIGKILL $$
}

function ctrl_c()
{
	echo "Y U no love me?!"
}

sudo sh -c 'echo $$ >> /var/run/holbertonscript.pid'

while true
do
    echo "To infinity and beyond"
    sleep 2
done
