#!/usr/bin/env bash
# This script is displaying 100 first number
# For number divisible by 3 and 5, show "FizzBuzz"
# For number divisible by 3, show "Fizz" 
# For number divisible by 5, show "Buzz"
# Ifnot show number
for i in {1..100}
do
	if (( i % 15 == 0 )); then
		echo "FizzBuzz"
	elif (( i % 3 == 0 )); then
		echo "Fizz"
	elif (( i % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
