#!/usr/bin/env bash
# This script that displays the content of the file /etc/passwd.

file="/etc/passwd"

while IFS=: read -r username _ userid _ _ homedir _
do    
    echo "$username:$userid:$homedir"
done < $file
