#!/usr/bin/env bash
#get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it.

sudo service apache2 status

if [ "$?" -gt 0 ]; then
	sudo service apache2 start;
fi
